#!/usr/bin/env node

/**
 * HRMS VM START SCRIPT
 * Pulls latest code, installs deps, and starts backend + frontend for VM/LAN testing.
 *
 * Usage:  node start-vm.js
 * Prereqs: git, node/npm, python3 venv already created at backend/venv/
 */

const { execSync, spawn } = require("child_process");
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const BACKEND_DIR = path.join(ROOT, "backend");
const FRONTEND_DIR = path.join(ROOT, "frontend");
const PYTHON = path.join(BACKEND_DIR, "venv", "bin", "python");

const VM_IP = "192.168.1.19";
const BACKEND_PORT = 3000;
const FRONTEND_PORT = 5173;

let backendProcess = null;
let frontendProcess = null;

function log(msg) {
  const t = new Date().toISOString().replace("T", " ").slice(0, 19);
  console.log(`[HRMS ${t}] ${msg}`);
}

function run(cmd, cwd = ROOT) {
  log(`$ ${cmd}`);
  execSync(cmd, { cwd, stdio: "inherit" });
}

// ─── Step 1: Pull latest code from development branch ────────────────────────
function pullLatestCode() {
  log("Pulling latest code from development branch...");
  try {
    run("git fetch origin");
    run("git checkout development");
    run("git pull origin development");
    log("Code updated successfully.");
  } catch (err) {
    log(`WARNING: git pull failed (${err.message}). Continuing with local code.`);
  }
}

// ─── Step 2: Write frontend/.env with VM API URL ─────────────────────────────
function writeFrontendEnv() {
  const envPath = path.join(FRONTEND_DIR, ".env");
  const content = [
    `# Auto-generated by start-vm.js — do not edit manually`,
    `VITE_API_URL=http://${VM_IP}:${BACKEND_PORT}`,
    `VITE_API_TIMEOUT_MS=30000`,
    `VITE_PARSING_API_URL=http://${VM_IP}:${BACKEND_PORT}`,
  ].join("\n") + "\n";

  fs.writeFileSync(envPath, content, "utf8");
  log(`Wrote frontend/.env  →  VITE_API_URL=http://${VM_IP}:${BACKEND_PORT}`);
}

// ─── Step 3: Install frontend npm dependencies if node_modules is missing ────
function installFrontendDeps() {
  const nm = path.join(FRONTEND_DIR, "node_modules");
  if (!fs.existsSync(nm)) {
    log("frontend/node_modules not found — running npm install...");
    run("npm install", FRONTEND_DIR);
  } else {
    log("frontend/node_modules present — skipping npm install.");
  }
}

// ─── Step 4: Install backend pip dependencies if venv is present ─────────────
function installBackendDeps() {
  if (!fs.existsSync(PYTHON)) {
    log(`WARNING: venv not found at ${PYTHON}. Create it first:`);
    log("  cd backend && python3 -m venv venv && venv/bin/pip install -r requirements.txt");
    return;
  }
  log("Installing/verifying backend pip dependencies...");
  try {
    const pip = path.join(BACKEND_DIR, "venv", "bin", "pip");
    run(`${pip} install -r requirements.txt --quiet`, BACKEND_DIR);
    log("Backend dependencies OK.");
  } catch (err) {
    log(`WARNING: pip install failed — ${err.message}`);
  }
}

// ─── Step 5: Start Flask backend ─────────────────────────────────────────────
function startBackend() {
  log("Starting Flask backend...");

  backendProcess = spawn(PYTHON, ["app.py"], {
    cwd: BACKEND_DIR,
    stdio: "inherit",
    env: { ...process.env, PYTHONIOENCODING: "utf-8" },
  });

  backendProcess.on("close", (code) => {
    log(`Backend stopped with exit code ${code}`);
  });
}

// ─── Step 6: Start Vite frontend ─────────────────────────────────────────────
function startFrontend() {
  log("Starting Vite frontend (bound to 0.0.0.0)...");

  // vite.config.js already sets host: "0.0.0.0"; --host flag is a safety net.
  frontendProcess = spawn("npm", ["run", "dev", "--", "--host", "0.0.0.0"], {
    cwd: FRONTEND_DIR,
    stdio: "inherit",
    shell: true,
  });

  frontendProcess.on("close", (code) => {
    log(`Frontend stopped with exit code ${code}`);
  });
}

// ─── Graceful shutdown ────────────────────────────────────────────────────────
function shutdown() {
  log("Stopping services...");
  if (backendProcess) backendProcess.kill("SIGTERM");
  if (frontendProcess) frontendProcess.kill("SIGTERM");
  process.exit(0);
}

// ─── Main ─────────────────────────────────────────────────────────────────────
function main() {
  console.log("\n======================================");
  console.log("        HRMS VM START SCRIPT");
  console.log("======================================\n");

  pullLatestCode();
  writeFrontendEnv();
  installFrontendDeps();
  installBackendDeps();

  startBackend();
  startFrontend();

  console.log("\n--------------------------------------");
  console.log(`  Backend:  http://${VM_IP}:${BACKEND_PORT}`);
  console.log(`  Frontend: http://${VM_IP}:${FRONTEND_PORT}`);
  console.log("--------------------------------------");
  console.log("  Press Ctrl+C to stop.\n");

  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);
}

main();
