/**
 * PDF Report Generator for Head of HR — HR Intelligence
 * Uses jsPDF + jspdf-autotable to produce professional PDF reports.
 */
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { getApplicationDisplayMatch, withReconciledScores, getDecisionSummary } from '@/features/analytics/components/MatchExplanation'

// ─── Theme colours ────────────────────────────────────────────────────────────
const C = {
  primary:    [30,  30,  80],
  accent:     [79,  70,  229],
  accentLt:   [237, 233, 254],
  headerBg:   [30,  30,  80],
  headerTxt:  [255, 255, 255],
  rowAlt:     [248, 248, 255],
  rowEven:    [255, 255, 255],
  border:     [200, 200, 220],
  text:       [30,  30,  30],
  muted:      [100, 100, 120],
  summaryBg:  [245, 245, 255],
  green:      [22,  163, 74],
  red:        [220, 38,  38],
  grey:       [107, 114, 128],
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
export function todayStr() {
  return new Date().toISOString().split('T')[0]
}
function nowFull() {
  return new Date().toLocaleString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long',
    day: 'numeric', hour: '2-digit', minute: '2-digit',
  }) + ' UTC'
}
function fmtDate(ts) {
  if (!ts) return '—'
  return new Date(ts).toLocaleDateString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
  })
}
function safe(v) {
  return (v != null && v !== '') ? String(v) : '—'
}
function setColor(doc, arr) {
  doc.setTextColor(arr[0], arr[1], arr[2])
}

// ─── Shared page decorations ─────────────────────────────────────────────────
function drawPageHeader(doc, title, subtitle) {
  const W = doc.internal.pageSize.getWidth()

  // Top accent bar
  doc.setFillColor(C.accent[0], C.accent[1], C.accent[2])
  doc.rect(0, 0, W, 18, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(255, 255, 255)
  doc.text('HR JOB PORTAL', 14, 12)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text('Head of HR Report', W - 14, 12, { align: 'right' })

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  setColor(doc, C.primary)
  doc.text(title, W / 2, 34, { align: 'center' })

  if (subtitle) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    setColor(doc, C.muted)
    doc.text(subtitle, W / 2, 41, { align: 'center' })
  }

  doc.setFontSize(8)
  setColor(doc, C.muted)
  doc.text('Generated on ' + nowFull(), 14, 48)

  doc.setDrawColor(C.border[0], C.border[1], C.border[2])
  doc.setLineWidth(0.5)
  doc.line(14, 51, W - 14, 51)

  return 56
}

// Content must stay above this Y so it doesn't overlap the footer
const FOOTER_ZONE_MM = 20

function drawPageFooter(doc) {
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const pages = doc.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setDrawColor(C.border[0], C.border[1], C.border[2])
    doc.setLineWidth(0.3)
    doc.line(14, H - 12, W - 14, H - 12)
    doc.setFontSize(7)
    setColor(doc, C.muted)
    doc.text('HR Intelligence — Confidential | Generated by Head of HR', 14, H - 7)
    doc.text('Page ' + i + ' of ' + pages, W - 14, H - 7, { align: 'right' })
  }
}

function drawSummaryBox(doc, y, items) {
  const W    = doc.internal.pageSize.getWidth()
  const colW = (W - 28) / items.length
  const boxH = 18

  doc.setFillColor(C.summaryBg[0], C.summaryBg[1], C.summaryBg[2])
  doc.setDrawColor(C.border[0], C.border[1], C.border[2])
  doc.setLineWidth(0.4)
  doc.roundedRect(14, y, W - 28, boxH, 2, 2, 'FD')

  items.forEach((item, i) => {
    const x  = 14 + i * colW
    if (i > 0) {
      doc.setDrawColor(C.border[0], C.border[1], C.border[2])
      doc.line(x, y + 2, x, y + boxH - 2)
    }
    const cx   = x + colW / 2
    const col  = item.color || C.accent
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    setColor(doc, col)
    doc.text(String(item.value), cx, y + 10, { align: 'center' })
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    setColor(doc, C.muted)
    doc.text(item.label, cx, y + 15.5, { align: 'center' })
  })

  return y + boxH + 6
}

function sectionHeading(doc, y, text) {
  const W = doc.internal.pageSize.getWidth()
  doc.setFillColor(C.accentLt[0], C.accentLt[1], C.accentLt[2])
  doc.rect(14, y, W - 28, 8, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  setColor(doc, C.primary)
  doc.text(text, 16, y + 5.5)
  return y + 10
}

function tableStyles(startY) {
  return {
    startY,
    margin: { left: 14, right: 14, bottom: FOOTER_ZONE_MM },
    styles: {
      fontSize: 8.5,
      cellPadding: { top: 3, bottom: 3, left: 4, right: 4 },
      lineColor: C.border,
      lineWidth: 0.3,
      textColor: C.text,
      font: 'helvetica',
    },
    headStyles: {
      fillColor: C.headerBg,
      textColor: C.headerTxt,
      fontStyle: 'bold',
      fontSize: 8.5,
    },
    alternateRowStyles: { fillColor: C.rowAlt },
    bodyStyles:         { fillColor: C.rowEven },
    tableLineColor:     C.border,
    tableLineWidth:     0.3,
  }
}

// ─── 1. Admins Report ─────────────────────────────────────────────────────────
export function generateAdminsPdf(admins) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  let y = drawPageHeader(doc, 'HR Admins Report', 'All registered HR administrators in the HR Intelligence system')

  const companies = [...new Set(admins.map((a) => a.company).filter(Boolean))]
  y = drawSummaryBox(doc, y, [
    { label: 'Total HR Admins',  value: admins.length },
    { label: 'Unique Companies', value: companies.length },
    { label: 'Report Date',      value: todayStr(), color: C.muted },
  ])

  y = sectionHeading(doc, y, 'Admin Account Details')
  autoTable(doc, {
    ...tableStyles(y),
    head: [['HR ID', 'Full Name', 'Email Address', 'Company', 'Date Joined']],
    body: admins.map((a) => [
      safe(a.hrid), safe(a.full_name), safe(a.email), safe(a.company), fmtDate(a.created_at),
    ]),
    columnStyles: {
      0: { cellWidth: 18, fontStyle: 'bold', textColor: C.accent },
      1: { cellWidth: 38 },
      2: { cellWidth: 55 },
      3: { cellWidth: 38 },
      4: { cellWidth: 32 },
    },
  })

  if (companies.length) {
    const afterY = doc.lastAutoTable.finalY + 8
    const hy = sectionHeading(doc, afterY, 'Companies Summary')
    autoTable(doc, {
      ...tableStyles(hy),
      head: [['Company', 'Admin Count']],
      body: companies.map((co) => [co, admins.filter((a) => a.company === co).length]),
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 30, halign: 'center', fontStyle: 'bold', textColor: C.accent },
      },
    })
  }

  drawPageFooter(doc)
  doc.save('admins-report-' + todayStr() + '.pdf')
}

// ─── 2. Candidates Report ─────────────────────────────────────────────────────
export function generateCandidatesPdf(candidates) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  let y = drawPageHeader(doc, 'Candidates Report', 'All registered candidates in the HR Intelligence system')

  const complete   = candidates.filter((c) => c.completed).length
  const incomplete = candidates.length - complete
  const locations  = [...new Set(candidates.map((c) => c.current_location).filter(Boolean))]

  y = drawSummaryBox(doc, y, [
    { label: 'Total Candidates',   value: candidates.length },
    { label: 'Profile Complete',   value: complete,   color: C.green },
    { label: 'Profile Incomplete', value: incomplete, color: incomplete ? C.red : C.grey },
    { label: 'Unique Locations',   value: locations.length },
  ])

  y = sectionHeading(doc, y, 'Candidate Details')
  autoTable(doc, {
    ...tableStyles(y),
    head: [['ID', 'Name', 'Email', 'Location', 'Experience', 'Profile', 'Joined']],
    body: candidates.map((c) => [
      safe(c.cid),
      safe(c.full_name || c.name),
      safe(c.email),
      safe(c.current_location),
      safe(c.experience_level),
      c.completed ? 'Complete' : 'Incomplete',
      fmtDate(c.created_at),
    ]),
    columnStyles: {
      0: { cellWidth: 16, fontStyle: 'bold', textColor: C.accent },
      1: { cellWidth: 30 },
      2: { cellWidth: 48 },
      3: { cellWidth: 28 },
      4: { cellWidth: 22 },
      5: { cellWidth: 20 },
      6: { cellWidth: 22 },
    },
    didDrawCell(data) {
      if (data.section === 'body' && data.column.index === 5) {
        if (data.cell.raw === 'Complete') {
          setColor(doc, C.green)
        } else {
          setColor(doc, C.red)
        }
      }
    },
  })

  drawPageFooter(doc)
  doc.save('candidates-report-' + todayStr() + '.pdf')
}

// ─── 3. Jobs Report ───────────────────────────────────────────────────────────
export function generateJobsPdf(jobs) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  let y = drawPageHeader(doc, 'Jobs Report', 'All job postings in the HR Intelligence system')

  const active    = jobs.filter((j) => j.enabled).length
  const disabled  = jobs.length - active
  const companies = [...new Set(jobs.map((j) => j.company).filter(Boolean))]

  y = drawSummaryBox(doc, y, [
    { label: 'Total Jobs',       value: jobs.length },
    { label: 'Active',           value: active,   color: C.green },
    { label: 'Disabled',         value: disabled, color: disabled ? C.red : C.grey },
    { label: 'Companies Hiring', value: companies.length },
  ])

  y = sectionHeading(doc, y, 'Job Listings')
  autoTable(doc, {
    ...tableStyles(y),
    head: [['Job ID', 'Title', 'Company', 'Location', 'Salary', 'Experience', 'Status', 'Posted By', 'Posted On']],
    body: jobs.map((j) => [
      safe(j.jdid), safe(j.title), safe(j.company), safe(j.location),
      safe(j.salary), safe(j.experience),
      j.enabled ? 'Active' : 'Disabled',
      safe(j.posted_by_name), fmtDate(j.posted_on),
    ]),
    columnStyles: {
      0: { cellWidth: 18, fontStyle: 'bold', textColor: C.accent },
      1: { cellWidth: 42 },
      2: { cellWidth: 32 },
      3: { cellWidth: 30 },
      4: { cellWidth: 24 },
      5: { cellWidth: 22 },
      6: { cellWidth: 18 },
      7: { cellWidth: 32 },
      8: { cellWidth: 26 },
    },
    didDrawCell(data) {
      if (data.section === 'body' && data.column.index === 6) {
        if (data.cell.raw === 'Active') {
          setColor(doc, C.green)
        } else {
          setColor(doc, C.red)
        }
      }
    },
  })

  drawPageFooter(doc)
  doc.save('jobs-report-' + todayStr() + '.pdf')
}

// ─── 4. Applications Report ───────────────────────────────────────────────────
export function generateApplicationsPdf(applications) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  let y = drawPageHeader(doc, 'Applications Report', 'All job applications with ATS match scores and status')

  const shortlisted = applications.filter((a) => a.shortlisted).length
  const pending     = applications.filter((a) => a.status === 'pending').length
  const rejected    = applications.filter((a) => a.status === 'rejected').length
  const scores      = applications.map((a) => a.match_score).filter((v) => v != null)
  const avgScore    = scores.length
    ? (scores.reduce((s, v) => s + v, 0) / scores.length).toFixed(1)
    : '—'

  y = drawSummaryBox(doc, y, [
    { label: 'Total Applications', value: applications.length },
    { label: 'Shortlisted',        value: shortlisted, color: C.green },
    { label: 'Pending',            value: pending,     color: C.grey },
    { label: 'Rejected',           value: rejected,    color: rejected ? C.red : C.grey },
    { label: 'Avg Match Score',    value: avgScore + '%', color: C.accent },
  ])

  // Group by job
  const byJob = {}
  applications.forEach((a) => {
    const key = a.job_id || 'unknown'
    if (!byJob[key]) {
      byJob[key] = { title: a.job_title, company: a.job_company, hr: a.hr_name, rows: [] }
    }
    byJob[key].rows.push(a)
  })

  const H = doc.internal.pageSize.getHeight()
  // Min space needed for a job section (heading + 2 subtitle lines + table start) so we don't overlap footer
  const sectionHeadHeight = 22

  let firstSection = true
  for (const [jobId, group] of Object.entries(byJob)) {
    let startY = firstSection ? y : (doc.lastAutoTable.finalY + 10)
    firstSection = false

    // If we're too close to the footer, start on a new page to avoid overlap
    if (startY > H - FOOTER_ZONE_MM - sectionHeadHeight) {
      doc.addPage('a4', 'landscape')
      startY = 18
    }

    const hy = sectionHeading(doc, startY, 'Job: ' + (group.title || jobId) + '  (' + jobId + ')')

    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    setColor(doc, C.muted)
    doc.text(
      'Company: ' + (group.company || '—') +
      '   |   HR Admin: ' + (group.hr || '—') +
      '   |   Total Applications: ' + group.rows.length,
      16, hy + 4,
    )
    const jobShortlisted = group.rows.filter((r) => r.shortlisted).length
    const jobScores      = group.rows.map((r) => r.match_score).filter((v) => v != null)
    const jobAvg         = jobScores.length
      ? (jobScores.reduce((s, v) => s + v, 0) / jobScores.length).toFixed(1)
      : '—'
    doc.text('Shortlisted: ' + jobShortlisted + '   |   Avg Match Score: ' + jobAvg + '%', 16, hy + 9)

    autoTable(doc, {
      ...tableStyles(hy + 12),
      head: [['#', 'Candidate ID', 'Candidate Name', 'Email', 'Match %', 'Shortlist', 'Status', 'Applied On']],
      body: group.rows.map((a, idx) => [
        idx + 1,
        safe(a.candidate_id),
        safe(a.candidate_name),
        safe(a.candidate_email),
        a.match_score != null ? Math.round(a.match_score) + '%' : '—',
        a.shortlisted ? 'Yes' : 'No',
        safe(a.status) || 'applied',
        fmtDate(a.applied_at),
      ]),
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: 22, fontStyle: 'bold', textColor: C.accent },
        2: { cellWidth: 38 },
        3: { cellWidth: 50 },
        4: { cellWidth: 18, halign: 'center', fontStyle: 'bold' },
        5: { cellWidth: 18, halign: 'center' },
        6: { cellWidth: 22, halign: 'center' },
        7: { cellWidth: 28 },
      },
      didDrawCell(data) {
        if (data.section === 'body') {
          if (data.column.index === 5) {
            if (data.cell.raw === 'Yes') {
              setColor(doc, C.green)
            } else {
              setColor(doc, C.grey)
            }
          }
          if (data.column.index === 6) {
            const v = data.cell.raw
            if (v === 'shortlisted') {
              setColor(doc, C.green)
            } else if (v === 'rejected') {
              setColor(doc, C.red)
            } else {
              setColor(doc, C.grey)
            }
          }
        }
      },
    })
  }

  drawPageFooter(doc)
  doc.save('applications-report-' + todayStr() + '.pdf')
}

// ─── 5. Full System PDF (cover + 4 sections) ─────────────────────────────────
export function generateFullSystemPdf(allData) {
  const { admins = [], candidates = [], jobs = [], applications = [] } = allData
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W   = doc.internal.pageSize.getWidth()

  // ── Cover page ──────────────────────────────────────────────────────────────
  doc.setFillColor(C.accent[0], C.accent[1], C.accent[2])
  doc.rect(0, 0, W, 60, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(26)
  doc.setTextColor(255, 255, 255)
  doc.text('HR Intelligence', W / 2, 28, { align: 'center' })
  doc.setFontSize(14)
  doc.setFont('helvetica', 'normal')
  doc.text('Full System Report', W / 2, 40, { align: 'center' })
  doc.setFontSize(9)
  doc.text(nowFull(), W / 2, 52, { align: 'center' })

  let cy = 75
  cy = drawSummaryBox(doc, cy, [
    { label: 'HR Admins',    value: admins.length },
    { label: 'Candidates',   value: candidates.length },
    { label: 'Jobs',         value: jobs.length },
    { label: 'Applications', value: applications.length },
  ])

  cy += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  setColor(doc, C.primary)
  doc.text('Contents', 14, cy)
  cy += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  setColor(doc, C.text)
  ;['1.  HR Admins', '2.  Candidates', '3.  Jobs', '4.  Applications'].forEach((s) => {
    doc.text(s, 22, cy)
    cy += 6
  })

  // ── Section 1: Admins ───────────────────────────────────────────────────────
  doc.addPage('a4', 'portrait')
  let y = drawPageHeader(doc, '1. HR Admins Report', 'All registered HR administrators')
  const adminCos = [...new Set(admins.map((a) => a.company).filter(Boolean))]
  y = drawSummaryBox(doc, y, [
    { label: 'Total HR Admins', value: admins.length },
    { label: 'Companies',       value: adminCos.length },
  ])
  y = sectionHeading(doc, y, 'Admin Accounts')
  autoTable(doc, {
    ...tableStyles(y),
    head: [['HR ID', 'Full Name', 'Email', 'Company', 'Joined']],
    body: admins.map((a) => [safe(a.hrid), safe(a.full_name), safe(a.email), safe(a.company), fmtDate(a.created_at)]),
    columnStyles: { 0: { cellWidth: 18, fontStyle: 'bold', textColor: C.accent }, 2: { cellWidth: 55 } },
  })

  // ── Section 2: Candidates ───────────────────────────────────────────────────
  doc.addPage('a4', 'portrait')
  y = drawPageHeader(doc, '2. Candidates Report', 'All registered candidates')
  const cComplete = candidates.filter((c) => c.completed).length
  y = drawSummaryBox(doc, y, [
    { label: 'Total Candidates', value: candidates.length },
    { label: 'Profile Complete', value: cComplete, color: C.green },
    { label: 'Incomplete',       value: candidates.length - cComplete, color: C.red },
  ])
  y = sectionHeading(doc, y, 'Candidate List')
  autoTable(doc, {
    ...tableStyles(y),
    head: [['ID', 'Name', 'Email', 'Location', 'Profile', 'Joined']],
    body: candidates.map((c) => [safe(c.cid), safe(c.full_name || c.name), safe(c.email), safe(c.current_location), c.completed ? 'Complete' : 'Incomplete', fmtDate(c.created_at)]),
    columnStyles: { 0: { cellWidth: 16, fontStyle: 'bold', textColor: C.accent }, 2: { cellWidth: 55 } },
  })

  // ── Section 3: Jobs ─────────────────────────────────────────────────────────
  doc.addPage('a4', 'landscape')
  y = drawPageHeader(doc, '3. Jobs Report', 'All job postings')
  const activeJ = jobs.filter((j) => j.enabled).length
  y = drawSummaryBox(doc, y, [
    { label: 'Total Jobs', value: jobs.length },
    { label: 'Active',     value: activeJ,             color: C.green },
    { label: 'Disabled',   value: jobs.length - activeJ, color: C.red },
  ])
  y = sectionHeading(doc, y, 'Job Listings')
  autoTable(doc, {
    ...tableStyles(y),
    head: [['Job ID', 'Title', 'Company', 'Location', 'Salary', 'Experience', 'Status', 'Posted By', 'Posted On']],
    body: jobs.map((j) => [safe(j.jdid), safe(j.title), safe(j.company), safe(j.location), safe(j.salary), safe(j.experience), j.enabled ? 'Active' : 'Disabled', safe(j.posted_by_name), fmtDate(j.posted_on)]),
    columnStyles: { 0: { cellWidth: 18, fontStyle: 'bold', textColor: C.accent }, 1: { cellWidth: 40 } },
  })

  // ── Section 4: Applications ─────────────────────────────────────────────────
  doc.addPage('a4', 'landscape')
  y = drawPageHeader(doc, '4. Applications Report', 'All job applications with match scores')
  const sCount    = applications.filter((a) => a.shortlisted).length
  const appScores = applications.map((a) => a.match_score).filter((v) => v != null)
  const appAvg    = appScores.length
    ? (appScores.reduce((s, v) => s + v, 0) / appScores.length).toFixed(1)
    : '—'
  y = drawSummaryBox(doc, y, [
    { label: 'Total',       value: applications.length },
    { label: 'Shortlisted', value: sCount,        color: C.green },
    { label: 'Avg Match',   value: appAvg + '%',  color: C.accent },
  ])
  y = sectionHeading(doc, y, 'Applications')
  autoTable(doc, {
    ...tableStyles(y),
    head: [['#', 'Candidate', 'Email', 'Job Title', 'Match %', 'Shortlisted', 'Status', 'Applied']],
    body: applications.map((a, i) => [
      i + 1, safe(a.candidate_name), safe(a.candidate_email), safe(a.job_title),
      a.match_score != null ? Math.round(a.match_score) + '%' : '—',
      a.shortlisted ? 'Yes' : 'No', safe(a.status), fmtDate(a.applied_at),
    ]),
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      2: { cellWidth: 50 },
      4: { cellWidth: 18, halign: 'center', fontStyle: 'bold' },
    },
  })

  drawPageFooter(doc)
  doc.save('hr-portal-full-report-' + todayStr() + '.pdf')
}

// ─── 6. Single Application & Match Report ─────────────────────────────────────
function chipsFromItems(items) {
  const out = []
  const arr = Array.isArray(items)
    ? items
    : (items && typeof items === 'object' ? Object.values(items) : [])
  arr.forEach((item) => {
    const s = String(item).trim()
    if (!s) return
    const colon = s.indexOf(': ')
    if (colon !== -1) {
      s.slice(colon + 2).split(',').map((x) => x.trim()).filter(Boolean).forEach((x) => out.push(x))
    } else {
      out.push(s)
    }
  })
  return out
}

function ensureSpace(doc, y, needed = 28) {
  const H = doc.internal.pageSize.getHeight()
  if (y > H - FOOTER_ZONE_MM - needed) {
    doc.addPage('a4', 'portrait')
    return 18
  }
  return y
}

function addWrappedText(doc, text, x, y, maxWidth, lineHeight = 5) {
  const lines = doc.splitTextToSize(String(text || ''), maxWidth)
  doc.text(lines, x, y)
  return y + lines.length * lineHeight
}

/**
 * Generate a PDF for one candidate's Application & Match analysis.
 * @param {object} application — application detail (with ats_analysis when available)
 * @param {{ jobTitle?: string }} [options]
 */
export function generateApplicationMatchPdf(application, options = {}) {
  if (!application) throw new Error('No application data to export')

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const jobTitle = options.jobTitle || application.job_title || '—'
  const candidateName = application.candidate_name || 'Candidate'
  const displayMatch = getApplicationDisplayMatch(application)
  const score = displayMatch.score

  const analysis = application.ats_analysis != null && typeof application.ats_analysis === 'object'
    ? application.ats_analysis
    : {}
  const rawJsonOut = analysis?.json_output ?? analysis
  const { jsonOut, score: reconciledScore, verdict: reconciledVerdict } = withReconciledScores(rawJsonOut, {
    storedScore: application.match_score != null ? Math.round(Number(application.match_score)) : score,
  })
  const breakdown = jsonOut?.score_breakdown ?? {}
  const rawStrengths = Array.isArray(jsonOut?.key_strengths) ? jsonOut.key_strengths : []
  const rawGaps = Array.isArray(jsonOut?.key_gaps) ? jsonOut.key_gaps : []
  const verdict = (reconciledVerdict || (jsonOut?.verdict || (jsonOut?.decision || '').replace(/_/g, ' ') || '').trim())
  const evalReport = jsonOut?.evaluation_report ?? {}
  const skillsAnalysis = evalReport?.skills_analysis ?? {}
  const mandatoryPct = jsonOut?.mandatory_skills_match_pct ?? skillsAnalysis?.mandatory_skills_match_pct
  const decisionBullets = Array.isArray(evalReport?.final_decision_logic) ? evalReport.final_decision_logic : []
  const educationAssessment = evalReport?.education_certification_assessment
  const narrative = (jsonOut?.narrative || jsonOut?.final_reasoning || jsonOut?.rationale || application?.ats_reasoning || '').trim()
  const decisionSummary = getDecisionSummary(jsonOut, {
    score: reconciledScore ?? score,
    status: application.status,
    atsReasoning: application.ats_reasoning,
  })
  const requirementAnalysis = jsonOut?.requirement_analysis || null
  const status = String(application.status || '').toLowerCase()
  const displayVerdict = status === 'ats_failed' ? 'ATS Failed' : (verdict || '—')

  let verdictReason = decisionSummary || 'See detailed analysis below.'
  if (status === 'ats_failed') {
    verdictReason = application.ats_reasoning || 'ATS matching failed for this application.'
  } else if (!decisionSummary && mandatoryPct != null && Number(mandatoryPct) < 40) {
    const missing = (requirementAnalysis?.mandatory || [])
      .filter((r) => r.status === 'missing')
      .map((r) => r.skill)
      .slice(0, 5)
    const extra = missing.length ? ` Still missing: ${missing.join(', ')}.` : ''
    verdictReason = `Low match: only ${Number(mandatoryPct)}% of mandatory skills matched (need at least 40%).${extra}`
  } else if (!decisionSummary && verdict && /not a match/i.test(verdict) && score != null) {
    verdictReason = `Low match: overall score is ${score}%, below the review floor for this role.`
  } else if (!decisionSummary && narrative) {
    verdictReason = narrative.split(/\n/)[0]?.trim().slice(0, 280) || verdictReason
  }

  let y = drawPageHeader(
    doc,
    'Application & Match Report',
    candidateName + '  ·  ' + jobTitle,
  )

  y = drawSummaryBox(doc, y, [
    { label: 'Match Score', value: score != null ? score + '%' : '—', color: score != null && score < 60 ? C.red : C.accent },
    { label: 'Verdict', value: displayVerdict.slice(0, 18), color: /not a match|failed/i.test(displayVerdict) ? C.red : C.green },
    { label: 'Status', value: application.shortlisted ? 'Shortlisted' : safe(application.status) },
    { label: 'Applied', value: fmtDate(application.applied_at), color: C.muted },
  ])

  y = sectionHeading(doc, y, 'Application Overview')
  autoTable(doc, {
    ...tableStyles(y),
    head: [['Field', 'Value']],
    body: [
      ['Candidate', safe(candidateName)],
      ['Email', safe(application.candidate_email)],
      ['Job', safe(jobTitle)],
      ['Job ID', safe(application.job_id || application.jobId)],
      ['Candidate ID', safe(application.candidate_id || application.candidateId)],
      ['Recruiter', safe(application.hr_name)],
      ['Match Score', score != null ? score + '%' : '—'],
      ['Verdict', safe(displayVerdict)],
      ['Status', application.shortlisted ? 'Shortlisted' : safe(application.status)],
      ['Applied On', fmtDate(application.applied_at)],
      ['Mandatory Skills Match', mandatoryPct != null ? Number(mandatoryPct) + '%' : '—'],
    ],
    columnStyles: {
      0: { cellWidth: 55, fontStyle: 'bold', textColor: C.accent },
      1: { cellWidth: 125 },
    },
  })
  y = doc.lastAutoTable.finalY + 8

  const SCORE_FACTORS = [
    { name: 'Core Skills', key: 'skills', weight: 60 },
    { name: 'Experience', key: 'experience', weight: 25 },
    { name: 'Education', key: 'education', weight: 10 },
    { name: 'Location', key: 'location', weight: 5 },
  ]
  const breakdownRows = SCORE_FACTORS
    .filter(({ key }) => breakdown[key] != null)
    .map(({ name, key, weight }) => [
      name,
      Math.round(Number(breakdown[key])) + '%',
      weight + '%',
    ])

  if (breakdownRows.length) {
    y = ensureSpace(doc, y, 40)
    y = sectionHeading(doc, y, 'Score Breakdown')
    autoTable(doc, {
      ...tableStyles(y),
      head: [['Factor', 'Score', 'Weight']],
      body: breakdownRows,
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 40, halign: 'center', fontStyle: 'bold', textColor: C.accent },
        2: { cellWidth: 40, halign: 'center' },
      },
    })
    y = doc.lastAutoTable.finalY + 8
  }

  y = ensureSpace(doc, y, 36)
  y = sectionHeading(doc, y, 'Why This Verdict')
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  setColor(doc, C.text)
  y = addWrappedText(doc, verdictReason, 16, y + 2, W - 32, 5)
  y += 6

  const scoreMath = jsonOut?.score_math
  const mathRows = Array.isArray(scoreMath?.rows) ? scoreMath.rows : []
  if (mathRows.length) {
    y = ensureSpace(doc, y, 40)
    y = sectionHeading(doc, y, 'How The Score Was Calculated')
    autoTable(doc, {
      ...tableStyles(y),
      head: [['Category', 'Score', 'Weight', 'Points']],
      body: [
        ...mathRows.map((r) => [r.label, `${r.raw_pct}%`, `${r.weight_pct}%`, String(r.points)]),
        ['Overall match score', '', '', String(scoreMath.total ?? score ?? '—')],
      ],
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 30, halign: 'center' },
        2: { cellWidth: 30, halign: 'center' },
        3: { cellWidth: 40, halign: 'center', fontStyle: 'bold', textColor: C.accent },
      },
    })
    y = doc.lastAutoTable.finalY + 4
    if (scoreMath.equation) {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      setColor(doc, C.muted)
      y = addWrappedText(doc, 'Math: ' + scoreMath.equation, 16, y, W - 32, 4)
      y += 6
    }
  }

  const NOISE = new Set([
    'preferred qualifications', 'plus', 'management', 'for', 'and', 'bonus points', 'public', 'job',
  ])
  const isClean = (s) => {
    const t = String(s || '').trim().toLowerCase()
    if (!t || NOISE.has(t)) return false
    const words = t.split(/\s+/)
    if (words.length && ['for', 'with', 'and', 'or', 'of'].includes(words[words.length - 1])) return false
    return true
  }

  const mandRows = Array.isArray(requirementAnalysis?.mandatory) ? requirementAnalysis.mandatory : []
  const prefRows = Array.isArray(requirementAnalysis?.preferred) ? requirementAnalysis.preferred : []
  let reqRows = [
    ...mandRows.filter((r) => isClean(r.skill)).map((r) => ['Mandatory', r.skill, r.status === 'matched' ? 'Matched' : 'Missing']),
    ...prefRows.filter((r) => isClean(r.skill)).map((r) => ['Preferred', r.skill, r.status === 'matched' ? 'Matched' : 'Missing']),
  ]
  if (!reqRows.length) {
    const missingMand = (skillsAnalysis.missing_mandatory_skills || []).filter(isClean)
    const missingPref = (skillsAnalysis.missing_preferred_skills || []).filter(isClean)
    const matched = (skillsAnalysis.skills_matched || skillsAnalysis.mandatory_matched_skills || []).filter(isClean)
    reqRows = [
      ...matched.map((s) => ['Mandatory', s, 'Matched']),
      ...missingMand.map((s) => ['Mandatory', s, 'Missing']),
      ...missingPref.map((s) => ['Preferred', s, 'Missing']),
    ]
  }
  if (reqRows.length) {
    y = ensureSpace(doc, y, 40)
    y = sectionHeading(doc, y, 'Requirements Checklist')
    autoTable(doc, {
      ...tableStyles(y),
      head: [['Tier', 'Skill', 'Status']],
      body: reqRows,
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 105 },
        2: { cellWidth: 40, halign: 'center' },
      },
    })
    y = doc.lastAutoTable.finalY + 8
  }

  const strengths = chipsFromItems(rawStrengths)
  const gaps = chipsFromItems(rawGaps)

  if (strengths.length) {
    y = ensureSpace(doc, y, 36)
    y = sectionHeading(doc, y, 'Strengths')
    autoTable(doc, {
      ...tableStyles(y),
      head: [['#', 'Strength']],
      body: strengths.map((s, i) => [i + 1, s]),
      columnStyles: { 0: { cellWidth: 12, halign: 'center' }, 1: { cellWidth: 168 } },
    })
    y = doc.lastAutoTable.finalY + 8
  }

  if (gaps.length) {
    y = ensureSpace(doc, y, 36)
    y = sectionHeading(doc, y, 'Gaps')
    autoTable(doc, {
      ...tableStyles(y),
      head: [['#', 'Gap']],
      body: gaps.map((s, i) => [i + 1, s]),
      columnStyles: { 0: { cellWidth: 12, halign: 'center' }, 1: { cellWidth: 168 } },
    })
    y = doc.lastAutoTable.finalY + 8
  }

  if (decisionBullets.length || educationAssessment || narrative) {
    y = ensureSpace(doc, y, 40)
    y = sectionHeading(doc, y, 'AI Match Insight')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    setColor(doc, C.text)

    if (narrative) {
      y = ensureSpace(doc, y, 24)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8.5)
      setColor(doc, C.muted)
      doc.text('Summary', 16, y)
      y += 5
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      setColor(doc, C.text)
      y = addWrappedText(doc, narrative, 16, y, W - 32, 5)
      y += 4
    }
    if (decisionBullets.length) {
      decisionBullets.forEach((bullet) => {
        y = ensureSpace(doc, y, 16)
        y = addWrappedText(doc, '• ' + bullet, 16, y, W - 32, 5)
        y += 2
      })
      y += 2
    }
    if (educationAssessment) {
      y = ensureSpace(doc, y, 20)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8.5)
      setColor(doc, C.muted)
      doc.text('Education / Certification', 16, y)
      y += 5
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      setColor(doc, C.text)
      y = addWrappedText(doc, educationAssessment, 16, y, W - 32, 5)
      y += 4
    }
  }

  drawPageFooter(doc)
  const slug = String(candidateName).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'candidate'
  doc.save('match-report-' + slug + '-' + todayStr() + '.pdf')
}
