"""Constants for Document Processing Engine."""

STAGE_ID = "STAGE-EXTRACTOR"
STAGE_VERSION = "1.0.0"
FACTORY_VERSION = "1.0.0"
ENGINE_VERSION = "1.0.0"
HASH_PREFIX = "sha256:"
MIN_EXTRACTED_CHARS = 30
TEXT_LAYER_MIN_CHARS = 10
